apiVersion: v1
kind: Service
metadata:
  name: wms-gateway
  namespace: wms
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: wms-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wms-gateway
  namespace: wms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wms-gateway
  template:
    metadata:
      labels:
        app: wms-gateway
    spec:
      containers:
        - name: wms-gateway
          image: wms/wms-gateway:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://wms-discovery:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: wms-gateway
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
            - name: WMS_SYSTEM_SERVICE_URI
              value: http://wms-system-service:8082
            - name: WMS_MASTERDATA_SERVICE_URI
              value: http://wms-masterdata-service:8083
            - name: WMS_BUSINESS_SERVICE_URI
              value: http://wms-business-service:8084
            - name: WMS_AGENT_SERVICE_URI
              value: http://wms-agent-service:8085
          ports:
            - name: http
              containerPort: 8080
