server:
  port: 8761

spring:
  application:
    name: wms-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    enable-self-preservation: false
