apiVersion: v1
kind: Service
metadata:
  name: wms-discovery
  namespace: {{ include "wms.namespace" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.services.discovery.port }}
      targetPort: {{ .Values.services.discovery.port }}
  selector:
    app: wms-discovery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wms-discovery
  namespace: {{ include "wms.namespace" . }}
spec:
  replicas: {{ .Values.replicaCount.discovery }}
  selector:
    matchLabels:
      app: wms-discovery
  template:
    metadata:
      labels:
        app: wms-discovery
    spec:
      containers:
        - name: wms-discovery
          image: {{ include "wms.image" (dict "root" . "imageName" .Values.services.discovery.imageName) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.discovery.port }}
