apiVersion: v1
kind: Secret
metadata:
  name: wms-mysql-secret
  namespace: {{ include "wms.namespace" . }}
type: Opaque
stringData:
  root-password: {{ .Values.mysql.rootPassword | quote }}
  username: {{ .Values.mysql.username | quote }}
  password: {{ .Values.mysql.password | quote }}
