server:
  port: 8084
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: wms-business-service
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3317/wms_cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:wms}
    password: ${DB_PASSWORD:wms123456}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
